// To make our products more functional using JS arrays
const data = {
    products: [
        {
            _id: '1',
            name: 'Aqua-wedding dress',
            category: 'Weeding Gown',
            image: '/images/product-1.jpg',
            price: 100000,
            brand: 'AllaGown',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Asda-wedding-dresses',
            category: 'Weeding Gown',
            image: '/images/product-2.jpg',
            price: 80000,
            brand: 'Asda',
            rating: 4.0,
            numReviews: 25,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Simple-wedding dress',
            category: 'Weeding Gown',
            image: '/images/product-3.jpg',
            price: 40000,
            brand: 'AllaGown',
            rating: 4.0,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Gold-wedding ring',
            category: 'Weeding Ring',
            image: '/images/product-4.jpg',
            price: 45000,
            brand: 'House of Craft',
            rating: 4.5,
            numReviews: 20,
            description: 'Gold plated product',
        },
        {
            _id: '5',
            name: 'Silver-wedding ring',
            category: 'Weeding Ring',
            image: '/images/product-5.jpg',
            price: 150000,
            brand: 'House of craft',
            rating: 4.5,
            numReviews: 50,
            description: 'Silver plated product',
        },
        {
            _id: '6',
            name: 'White wedding shoe',
            category: 'Shoe',
            image: '/images/product-6.jpg',
            price: 45000,
            brand: 'Varserce',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
}; 
export default data